server:
  port: 8081

spring:
    datasource:
          name: test
          url: jdbc:mysql://192.168.21.129:3306/mysql
          username: javaee
          password: java
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
custom:
    datasource:
        names: ds1,ds2
        ds1:
          driver-class-name: com.mysql.jdbc.Driver
          name: test
          url: jdbc:mysql://192.168.21.130:3306/mysql
          username: javaee
          password: java
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
        ds2:
          driver-class-name: com.mysql.jdbc.Driver
          name: test
          url: jdbc:mysql://192.168.21.131:3306/mysql
          username: javaee
          password: java
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: com.pingan.pojo
  
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
management:
    security: 
      enabled: false